### PR TITLE
Add 'assigned' status; remove 'in_progress' status

### PR DESCRIPTION
**Pull request by otterbotter**
Removes 'in_progress' status and instead sets 'assigned' status. Conditions changed accordingly.

### CODE REVIEW

**Comment by jbothma** [comment]
we also need a migration for anything currently with the status "in_progress", right?

**Comment by jbothma** [comment]
beyond that, ship it when you're ready, along with the frontend change

**Comment by otterbotter** [comment]
> we also need a migration for anything currently with the status "in_progress", right?

I don't think we need to since the status values are mapped in our db when we update from collaborator, which is when we get a detail or list, so they'll be set to the new value before they reach the frontend.

**Comment by otterbotter** [comment]
> beyond that, ship it when you're ready, along with the frontend change

please approve the PR ❤️

**Review by jbothma — APPROVED** [review]

**Pull request merged**
